# ./dbt/profiles.yml
tsql_eval_duckdb:
  target: duck
  outputs:
    duck:
      type: duckdb
      # 로컬/CI 공통 경로 (환경변수 없으면 기본값 사용)
      path: "{{ env_var('DUCKDB_PATH', 'data/nyc_taxi.duckdb') }}"
      threads: 4
      schema: nyc
      extensions:
        - httpfs
        - parquet
      settings:
        timezone: "UTC"
