# dbt/profiles.yml
tsql_eval:
  target: sqlite
  outputs:
    sqlite:
      type: sqlite
      threads: 1
      database: "sample"
      schema: "main"
      schemas_and_paths:
        main: "{{ env_var('DBT_ROOT') }}/data/sample.db"
      schema_directory: "{{ env_var('DBT_ROOT') }}/data"

    duck:
      type: duckdb
      threads: 4
      path: "{{ env_var('DBT_ROOT') }}/data/sample.duckdb"
      schema: "main"
