version: 2

models:
  - name: stg_departments
    description: "View of departments"
    columns:
      - name: id
        tests: [not_null]
      - name: name
        tests:
          - not_null
          - unique

  - name: stg_employees
    description: "View of employees"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: dept_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_departments')
                field: id

  - name: agg_avg_salary
    description: "Average salary per department"
    columns:
      - name: dept
        tests: [not_null]
      - name: avg_salary
        tests: [not_null]
