name: Build & Deploy dbt-colibri Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'dbt/**'
      - 'scripts/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'Makefile'
      - '.github/workflows/colibri-pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user uv
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Sync deps
        run: |
          uv venv
          uv sync

      - name: Prepare sample DB
        run: uv run python scripts/setup_db.py

      - name: Build dbt artifacts (manifest/catalog)
        env:
          DBT_ROOT: ${{ github.workspace }}
          DBT_PROFILES_DIR: ./dbt
        run: |
          uv run dbt build --project-dir dbt
          uv run dbt compile --project-dir dbt
          uv run dbt docs generate --project-dir dbt

      - name: Generate colibri site
        working-directory: dbt
        run: uv run colibri generate

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dbt/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
